### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ps-dms-deploy#1]
Currently I'm getting an error when I attempt to access the SPARQL endpoint from a page not served by the server running the SPARQL endpoint (my app code is being served by `localhost`, the query is running against `ch-pub-dev`):

    sparql.html:1 XMLHttpRequest cannot load http://ch-pub-dev.epimorphics.net/ch/query?
    query=prefix+rdf%3A+%3Chttp%3A%2…chema%23%3E%0A%0Aselect+*+where%0A%7B%3Fs+%3Fp+%3Fo%7D+limit+20&output=tsv. 
    No 'Access-Control-Allow-Origin' header is present on the requested resource. 
    Origin 'http://localhost:9000' is therefore not allowed access.

Adding CORS would help the development process, and would be good future-proofing in case we decide to split presentation and data servers in future.

**Comment by bwm-epimorphics** [comment]
This is an issue against the CH chef cookbook - so transferring there.

https://epimorphics.codebasehq.com/projects/operations/tickets/173
